name: Test integration CI

on:
  issue_comment:
    types: [ created ]
    
jobs:
  build:
    if: github.event.issue.pull_request && github.event.comment.body == 'run integrations test'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: npm run test:integration
