name: Test integration CI

on:
  issue_comment:
    types: [ created ]
    
jobs:
  build:
    if: github.event.issue.pull_request && github.event.comment.body == 'run integrations test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - run: npm run test:integration
        env:
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
